### ISSUE TITLE
Support requiring OAuth scopes for routes

### ISSUE THREAD

**Issue by ajenkinski** [aws/chalice#1326]
When using the `CognitoUserPoolAuthorizer` authorizer, there doesn't seem to be any way to require specific OAuth scopes for routes, as is possible through the API Gateway console.  This would be a useful feature to add.  One possible API would be to add a `scopes` keyword argument to `Chalice.route()`, which allows specifying a list of OAuth scopes that are required for that endpoint.

```python
authorizer = CognitoUserPoolAuthorizer('MyAuth', ['pool_arn'])

@app.route('/admin_stuff', authorizer=authorizer, scopes=['myapp/admin'])
def admin_stuff():
    do_some_privileged_task()

@app.route('/normal_stuff', authorizer=authorizer, scopes=['myapp/user'])
def normal_stuff():
    do_normal_stuff()
```

The would result in the outputted swagger having security sections like:

```yaml
paths:
  /admin_stuff:
    get:
      ...
      security:
      - MyAuth: ['myapp/admin']
  /normal_stuff:
    get:
      ...
      security:
      - MyAuth: ['myapp/user']
```

Currently, from what I can tell from looking at the source, (I believe this is the relevant code in [swagger.py](https://github.com/aws/chalice/blob/master/chalice/deploy/swagger.py#L152)), it seems to be hardcoded to always emit an empty scopes list for the security section.
