### ISSUE TITLE
chalice detele from gitlabci

### ISSUE THREAD

**Issue by B-Seif** [aws/chalice#1428]
I'm using gitlabci to deploy my chalice app and I would like to know how to use the `chalice delete` command to delete the app (the entire stack), again from my gitlabci. I can't use the `chalice package` because of ` s3_event` issue, hence the use of `chalice deploy` in my CICD.

Can we for example get the name of cloudformation stack ? if so, I think use this 
`aws cloudformation delete-stack --stack-name  my-stack`
`
```yaml
stages:
  - deploy
  - stop

chalice-deploy:
  stage: deploy
  image: python:3.7.4
  script:
    - pip3 install awscli chalice 
    - chalice deploy
  artifacts:
     paths:
      - public

chalice-delete:
  stage: stop
  image: python:3.7.4
  when: manual
  script:
    - pip3 install awscli chalice
    - chalice delete ????  
````
