### ISSUE TITLE
Chalice Fails to Deploy In "python3" BitBucket Pipeline

### ISSUE THREAD

**Issue by digitalcircuits** [aws/chalice#1906]
I have a bitbucket-pipeline.yml:

```
image: python:3.8-buster

pipelines:
  branches:
    master:
      - step:
          name: deploy to aws
          script:
           - apt-get update && apt-get install -y awscli groff zip
           - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
           - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
           - aws configure set default.region us-east-1
           - pip install chalice
           - chalice deploy
```

requirements.txt
```
ansicon==1.89.0
attrs==21.4.0
blessed==1.19.1
botocore==1.24.24
chalice==1.26.6
click==8.0.4
colorama==0.4.4
inquirer==2.9.1
jinxed==1.1.0
jmespath==0.10.0
mypy-extensions==0.4.3
numpy==1.22.3
pandas==1.4.1
python-dateutil==2.8.2
python-editor==1.0.4
pytz==2022.1
PyYAML==6.0
readchar==3.0.5
six==1.16.0
urllib3==1.26.9
wcwidth==0.2.5
```

.chalice/config.json

```
{
  "version": "2.0",
  "app_name": "myservice-analytics-api",
  "stages": {
    "dev": {
      "api_gateway_stage": "api"
    }
  }
}

```

When attempting to deploy using Bitbucket pipeline, I get this error

![screenshot1](https://user-images.githubusercontent.com/59550818/159799011-c46cc8e3-6fe4-4b5b-892c-70dc9057d4b3.png)

I dont see this problem when I deploy using my Windows 11 PC so I am not sure whats going on.
