### ISSUE TITLE
Chalice generate-pipeline can create yaml incompatible with Cloudformation

### ISSUE THREAD

**Issue by corespace** [aws/chalice#450]
Hi folks,

I was working on a chalice app recently and decided to try out the chalice generate-pipeline feature. My app looked something like this:

```
from chalice import Chalice

app = Chalice(app_name='docGen')

@app.route('/some-path', methods=['POST'])
def generate_stuff():
    json_body = app.current_request.json_body
    return do_the_thing(json_body)
```
I've left out some details, obviously, but this is enough to see the problem. When I ran generate pipeline and deployed that pipeline, it built out a CloudFormation yaml that included this:
```
Resources:
  APIHandler:
    Properties:
      CodeUri: s3://some-s3-bucket
      Events:
        generate_stuffpostc666:
          Properties:
            Method: post
            Path: /some-path
            RestApiId:
              Ref: RestAPI
          Type: Api
      Handler: app.app
      MemorySize: 128
      Role: some-arn
      Runtime: python2.7
      Tags:
        aws-chalice: version=0.10.1:stage=dev:app=docGen
      Timeout: 60
    Type: AWS::Serverless::Function
```
Cool, right? Nope. Cloudformation barfed on this saying something to the effect "Event names must be alphanumeric" I don't have the exact error message anymore cause I went to retrieve it today and the ChangeSet is gone. Anyway, I created a test to reproduce the problem, but I'm not sure how you folks would want to rectify the problem. You can see it here: https://github.com/aws/chalice/compare/master...corespace:view_name?expand=1
